#!/bin/bash

# This block allows you to control the volume of 2 named PA sinks (audio
# outputs): normally your headphones or speakers.
#
# This script looks for 2 sinks defined in ~/.config/pulse/local_devices:
#  * headphones=<device name of your headphones>
#  * speakers=<device name of your speakers/line out>
# You can get more info on this by running "pacmd list-sinks".

# log prints a message with an optional priority, which controls the color also
# printed if a terminal is present. Messages always go to standard error.
#
# level is optional, and if not specified defaults to info.
log() {
  local message="$1"
  local level="$2"
  declare -A colors=(
    ["error"]="31"   # red
    ["warning"]="33" # yellow
    ["ok"]="32"      # green
    ["info"]="1"     # bold
    ["reset"]="0"    # here just to note reset code
  )
  if [[ -z "${level}" ]] || [[ -z "${colors[$level]}" ]]; then
    level="info"
  fi
  if [[ -t 1 ]]; then
    echo -e "\e[${colors[$level]}m${message}\e[0m" 1>&2
  else
    echo "${message}" 1>&2
  fi
}

# log_fatal is a "log MESSAGE error" followed by an "exit 1".
log_fatal() {
  local message="$1"
  log "${message}" error
  exit 1
}

declare -A pa_devices
while read -r line; do
  IFS="=" read -ra parts <<< "${line}"
  pa_devices["${parts[0]}"]="${parts[*]:1}"
done < "${HOME}/.config/pulse/local_devices"

if [[ -z "${pa_devices[headphones]}" ]]; then
  log_fatal "fatal: please define your headphones device in ~/.config/pulse/local_devices"
fi

if [[ -z "${pa_devices[speakers]}" ]]; then
  log_fatal "fatal: please define your speakers device in ~/.config/pulse/local_devices"
fi

# The mixer real-time signal. This will signal to the mixer to immediately
# update its volume reading upon switching inputs via this block.
mixer_signal="10"

# default_sink gets the default sink name.
default_sink() {
  local pacmd_out=""
  if ! pacmd_out=($(pacmd stat | grep 'Default sink name')); then
    return 1
  fi
  echo "${pacmd_out[-1]}"
}

# sink_id gets the sink ID for a specific name.
sink_id() {
  local name="$1"
  if ! pactl_out=($(pactl list short sinks | grep "${name}")); then
    return 1
  fi
  echo "${pactl_out[0]}"
}

# format displays a symbol depending on the current default sink - headphones
# or speakers.
format() {
  local sink_name=""
  if ! sink_name="$(default_sink)"; then
    return 1
  fi
  if [[ "${sink_name}" == "${pa_devices[headphones]}" ]]; then
    echo ""
  else
    echo ""
  fi
}

# move_sink_inputs moves all the sinks that are set to the old input to the new
# input.
move_sink_inputs() {
  local old="$1"
  local new="$2"
  local sink_inputs=""
  if ! sink_inputs=$(pactl list short sink-inputs | grep -E "^[0-9]{1,}[[:space:]]{1,}${old}" | awk '{print $1}'); then
    return 1
  fi
  for input in ${sink_inputs}; do
    if ! pacmd move-sink-input "${input}" "${new}"; then
      return 1
    fi
  done
}

# toggle_default switches the default between the headphone and speaker output.
toggle_default() {
  local current=""
  local current_id=""
  local new=""
  local new_id=""
  if ! current="$(default_sink)"; then
    log_fatal "fatal: error locating current input"
  fi
  if ! current_id="$(sink_id "${current}")"; then
    log_fatal "fatal: error locating sink ID for current input"
  fi
  case "${current}" in
    "${pa_devices[headphones]}")
      new="${pa_devices[speakers]}"
      ;;
    "${pa_devices[speakers]}")
      new="${pa_devices[headphones]}"
      ;;
    *)
      log_fatal "fatal: could not determine input type for default input: ${current}"
      ;;
  esac
  if ! new_id="$(sink_id "${new}")"; then
    log_fatal "fatal: error finding sink ID for new input"
  fi
  if ! pactl set-default-sink "${new}"; then
    log_fatal "fatal: error running pactl set-default-sink"
  fi
  if ! move_sink_inputs "${current_id}" "${new_id}"; then
    log_fatal "fatal: error moving sink inputs to new output"
  fi

  # Update the mixer's volume.
  kill -s "RTMIN+${mixer_signal}" "$(pidof i3blocks)"
}

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  3) toggle_default ;;  # right click, toggle default
esac

if ! format; then
  log_fatal "fatal: error rendering block"
fi
